### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by nesl247** [dracula/terminal-app#1]
Hey everyone,

We're looking for a maintainer for Terminal.app. Dracula theme has grown significantly and it's too much for one person. If you are interested in becoming the maintainer, please reply here.

We're not going to let issues and pull requests get behind though just because we don't have a dedicated maintainer, so fear not.

Thanks.
- Dracula Theme Team

**Comment by muyangwu** [comment]
Hi I would like to become the maintainer for Terminal.app. All your themes look awesome!

**Comment by benknoble** [comment]
Has this been resolved? I'm also interested in maintaining the theme, since I use it.

**Comment by nesl247** [comment]
Pinging @zenorocha. I'm not active with the project anymore due to time constraints.

**Comment by zenorocha** [comment]
That's great, just added you @benknoble ;)
