### ISSUE TITLE
Lacking step for terminal to display colors in BASH or the default shell for the Terminal App

### ISSUE THREAD

**Issue by octokas** [dracula/terminal-app#10]
Lacking step for terminal to display colors in BASH or the default shell for the Terminal App. To be helpful, instructions should mention that Users _(using 10.13.4 or later)_, should run:
```bash
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
```
<img width="994" alt="Screen Shot 2019-06-08 at 10 32 46 PM" src="https://user-images.githubusercontent.com/39838381/59154307-5da14900-8a3d-11e9-9c66-cb08e2b6a772.png">

**Comment by benknoble** [comment]
Please see #2, #3, #4, #7, etc. 

The colorscheme is meant to change the colors the Terminal uses to highlight text. It is up to the user to create/use colored prompts and commands with colored text. 

Additionally, installation instruction issues belong in the repo for the site (dracula/dracula.github.io)—the screenshot is using a custom zsh prompt anyway, not bash, so you’re instructions are not pertinent to all users (zsh uses %-escapes in its prompt string). 

Again, by my read, this falls into the user domain of customization. We just provide the color palette.
