### ISSUE TITLE
Windows 10 terminal support

### ISSUE THREAD

**Issue by edumaxsantos** [dracula/terminal-app#11]
Hello,

I'd like to know if there's a way to use dracula theme on the new Windows 10 Terminal.

Thank you for your time.

**Comment by benknoble** [comment]
Hello @edumaxsantos ! This repo is actually for the macOS Terminal.app.

I checked https://draculatheme.com and scrolled down to the **Terminals** section, but did not see anything related to Windows 10 (check for yourself, there's other goodies there!).

You could also check in the [dracula organization](https://github.com/dracula), particularly [here](https://github.com/dracula/dracula-theme) where we keep a list of all the repos.
