### ISSUE TITLE
Text wrapping on itself?

### ISSUE THREAD

**Issue by ysumath1** [dracula/terminal-app#12]
![image](https://user-images.githubusercontent.com/24642735/72576758-2f6ace00-3896-11ea-9773-b4a640808eca.png)

Hi, I seem to have an issue where the text for long lines seems to wrap over itself, instead of flowing onto a new line like it should. Not sure why this happened, and any advice you can give on how to fix it would be much appreciated.  StackExchange suggests something about a PS1 line?https://askubuntu.com/questions/24358/how-do-i-get-long-command-lines-to-wrap-to-the-next-line

Thanks! Would really appreciate any help here.

**Comment by ysumath1** [comment]
Okay fixed it and closing issue. Sorry, it's totally unrelated to Dracula. In the event someone else finds it helpful, this link explains how to correctly edit the PS1 line in ~/.bash_profile 

https://askubuntu.com/questions/24358/how-do-i-get-long-command-lines-to-wrap-to-the-next-line

**Comment by zenorocha** [comment]
Thanks for reporting back @ysumath1!

**Comment by benknoble** [comment]
Indeed, wrapping unprintables (such as color sequences) in `\[` and `\]` is too easy to forget, and causes just such issues as this. Glad it worked out.
