### ISSUE TITLE
Unsupported character

### ISSUE THREAD

**Issue by leonardobrito** [dracula/terminal-app#17]
Hi guys, I'm using my terminal with `oh-my-zsh` and with `ZSH_THEME="spaceship"`, and I got this unsupported character. Any idea how to make Dracula accept too? 🧛🏻‍♂️  

![Screen Shot 2021-09-24 at 17 26 49](https://user-images.githubusercontent.com/2532291/134736114-4d3ff13f-9791-4e6e-995a-7a551d5bbde8.png) 

![Screen Shot 2021-09-24 at 17 27 43](https://user-images.githubusercontent.com/2532291/134736134-95570aac-f6b4-45d0-9eee-5db8f35f46b9.png)

**Comment by leonardobrito** [comment]
Well, I realize what's wrong, at the homebrew terminal I'm using another font (`Fira Code`), so I just will change the font on Dracula Terminal too. I'll close this issue. 😅

**Comment by benknoble** [comment]
No worries! This is a font issue, though. It's hard to specify a good font in this repo, since I can't guarantee anything beyond what comes with the OS.
