### ISSUE TITLE
NOT AN ISSUE: can you please share ~/.bash_profile ?

### ISSUE THREAD

**Issue by dongwandonkim** [dracula/terminal-app#18]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
can you please share ~/.bash_profile ?
For the people who wanted to have exactly same theme as the screen shot on the website?

**Comment by benknoble** [comment]
There is no such `~/.bash_profile` to share.

This is mentioned in several places:

- On the README:
  > A caveat: this theme customizes (among other things) the colors Terminal.app uses to display colors. It does not automatically make your programs colorful! See some of the pinned issues on github for more information.
- The pinned issues: https://github.com/dracula/terminal-app/issues/2 (which links to several more!), https://github.com/dracula/terminal-app/issues/14
- Here, Zeno mentions it's a custom ZSH thing: https://github.com/dracula/terminal-app/issues/3#issuecomment-366296703

---

On the (hopefully harmless) assumption that you're a bit new to open source, I will note that it's polite to do the appropriate research/reading before asking a question. This one has been asked _a lot_, hence all the writing about it. If a quick look around did _not_ lead you to this information, I would be grateful for feedback on how I can make it easier to find.
