### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by twrogers1** [dracula/terminal-app#19]
Currently, the instructions available at https://draculatheme.com/terminal in the *Activating theme* section  are not totally accurate. All required UI navigation are not accounted for. Since the instructions are not contained in the readme, I'm unable to create a PR here, but instead I'm requesting the instructions be updated to the following:

1.  _Terminal_ > Preferences
2. Click the Profiles tab
3. In the left pane at the bottom, click "...", then _Import..._
4.  Browse to and select the `Dracula.terminal` file
5.  Click _Default_
6. Restart all open terminals

**Comment by benknoble** [comment]
The instructions are available in INSTALL.md for PRs.

**Comment by twrogers1** [comment]
Thanks, not sure how I missed that before. I've submitted a PR here - https://github.com/dracula/terminal-app/pull/20, and will close this issue for now.
