### ISSUE TITLE
Installing from brew does not work(?)

### ISSUE THREAD

**Issue by electfreak** [dracula/terminal-app#22]
What I did:
```shell
brew tap dracula/install
brew install --cask dracula-terminal
```
At the end:
```shell
The file /Users/electfreak/Dracula.terminal does not exist.
🍺  dracula-terminal was successfully installed!
```
Then I've tried to "import" profile but got nothing since I can't guess where file is located. I've triend to find a file with name "Dracula.terminal" but seems like there is no such. Theme did not appear in settings.

**Comment by benknoble** [comment]
I'll have to take a look; that installer is separate from this repo and I can't recall if I've ever messed with it.

**Comment by benknoble** [comment]
This must be the file https://github.com/dracula/homebrew-install/blob/main/Casks/dracula-terminal.rb

But I don't see a reference to `~/Dracula.terminal`.

I don't remember; are there "verbose" or "debug" options you can pass to `brew` to give more detailed logs during the execution of the installer? I would really love to see more information :)

**Comment by benknoble** [comment]
Actually, it might be the line `open #{app} #{theme}`; that seems wrong.

**Comment by benknoble** [comment]
@electfreak can you try the following?

1. `brew edit dracula-terminal`
2. Change `open -a #{app} #{theme}` to `open -a #{app} #{xml}`, save
3. Run `brew install --cask dracula.terminal`?

**Comment by electfreak** [comment]
I'm sorry for late response. In that day I've made it somehow, I've found that file somehow. But it was unintuitive and I think you might want to know about such issue.

**Comment by ivasilov** [comment]
This is still an issue. I'm getting the exact same error.

**Comment by benknoble** [comment]
> This is still an issue. I'm getting the exact same error.

Can you try the instructions in https://github.com/dracula/terminal-app/issues/22#issuecomment-1624206392 ? (I know that recent brew has changed how files are stored/edited, but if someone can confirm the code changes we can get a PR up.)

**Comment by thebergamo** [comment]
The workaround presented in comment #22 doesn't work. :(
![image](https://github.com/dracula/terminal-app/assets/1778730/65691945-ff83-4407-8461-d6d315f65d60)

Just one remark here, you need to use: `brew reinstall --cask dracula-terminal`

**Comment by benknoble** [comment]
Ah, crud. Seems `xml` holds the XML data, not the filename. Hm.

**Comment by thebergamo** [comment]
Yeah, so the file name itself is just `theme`, but doing some try/catch here I could see that for example the Dracula.Terminal is not being found and even when it's found (forcing open from the file in Caskroom) it causes error saying that Apple cannot check the file form Malwares because it's an unidentified developer. 


If I try to import the file directly it works fine.

**Comment by benknoble** [comment]
Might be time to just recommend deprecating the formula, then. It's definitely not the easiest thing. I didn't even create it, and I certainly don't maintain it 😅
