### ISSUE TITLE
Instructions are wrong for ohmyzsh themes lib step

### ISSUE THREAD

**Issue by ColtonIdle** [dracula/terminal-app#26]
https://draculatheme.com/zsh says

> Install manually
> Download using the [GitHub .zip download](https://github.com/dracula/zsh/archive/master.zip) option and unzip them.
> Move dracula.zsh-theme file to [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/)'s theme folder: oh-my-zsh/themes/dracula.zsh-theme.
> Move /lib to [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/)'s theme folder: oh-my-zsh/themes/lib.

I didn't see a `oh-my-zsh/themes/lib`, but there is `oh-my-zsh/lib` and once I put it in there, everything seemed to work fine. So I think basically the path can remove themes for the "lib" step. Cheers

**Comment by benknoble** [comment]
This is not the Zsh theme repo.
