### ISSUE TITLE
prompt and colors

### ISSUE THREAD

**Issue by mshahat** [dracula/terminal-app#3]
Hi, What is the prompt you're using on the screenshot on the website ? 

Thanks

**Comment by benknoble** [comment]
As mentioned in #4 I suspect it's a custom zsh theme but I really have no clue.

You can follow the discussion on bash prompts here at #2 if you want; I'm thinking about making it a wiki page.

**Comment by zenorocha** [comment]
Yeah, it's ZSH. Thanks for cleaning up those issues @benknoble!

**Comment by benknoble** [comment]
@zenorocha np. Figured that's the first step of a 'maintainer' in any project
