### ISSUE TITLE
Not seeing theme syntax

### ISSUE THREAD

**Issue by shahaba** [dracula/terminal-app#4]
Hi!

I followed the instructions on the dracula/terminal.app page, but my terminal doesn't show the syntax colouring. Is there something I might be doing wrong?

![screen shot 2017-12-15 at 11 31 05 pm](https://user-images.githubusercontent.com/6495706/34067330-758da802-e1f0-11e7-821d-a16b5066622b.png)

**Comment by benknoble** [comment]
@shahaba I think there's two things going on here:

1. The use of color in the terminal—certain programs have color in their output (e.g. `git`). For more color, you can e.g. customize your prompt (good discussion in #2 and the internet at large. you can also grab the details of my prompt script [here][benknoble] and then source it)
2. The highlighting of commands &c.—my guess here is that a screenshot was taken using a custom zsh prompt that does this.

With this in mind, I'm going to go ahead and close the issue, but if there are real bugs occurring in the theme please let me know.

[benknoble]: https://github.com/benknoble/Dotfiles/blob/master/bash/PS1.bash

**Comment by shahaba** [comment]
@benknoble Thank you for the info! I will follow up on what you mentioned

**Comment by benknoble** [comment]
@shahaba no problem ! Since I happened to point you to my dotfiles repo, feel free to poke around there and even chat with me on Gitter if you want to talk about command-line customization.
