### ISSUE TITLE
Update ANSI colors to match spec

### ISSUE THREAD

**Issue by benknoble** [dracula/terminal-app#6]
Thanks to the [spec][spec] created by @dsifford , we have the 'standard' ANSI values to use.

This issue tracks bringing Terminal.app in line with said spec.

[spec]: https://dsifford.github.io/dracula-spec/#sec-ANSI

**Comment by dsifford** [comment]
The spec document might be outdated. The ANSI colors were adjusted per recommendations of @marcdeop.

See https://github.com/dracula/dracula-theme/issues/232#issuecomment-321979481

**Comment by benknoble** [comment]
@dsifford So should I rely on the linked spec or the comment you mentioned ?

**Comment by dsifford** [comment]
The comment should be accurate I think
