### ISSUE TITLE
Color is not working

### ISSUE THREAD

**Issue by henry-w-cooper** [dracula/terminal-app#7]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

The color seems not working, look the screenshot. My Mac OS version is High Sierra 10.13.4 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/40123409/44400298-4318e480-a57d-11e8-980e-e8965647b8f0.png">

**Comment by benknoble** [comment]
Did you follow the [installation instructions](https://draculatheme.com/terminal/) ? You may need to do "New Terminal with Theme Dracula" or set Dracula to your default theme.

In fact, it appears you did install the theme (the background and font colors are correct). Your prompt string contains no color sequences, and your `ls` didn't use the color flag (`-G` on macOS I believe).

**Comment by benknoble** [comment]
That is, your terminal was displaying _non-colored_ text, and so of course there were no colors.

**Comment by henry-w-cooper** [comment]
Thanks. It become colorful after I modified the .bash_profile file.
