### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by rjconstantino** [dracula/terminal-app#8]
This is what my terminal looks like after installing the Dracula. Do I still need to do something?

<img width="585" alt="screen shot 2018-11-13 at 4 05 37 pm" src="https://user-images.githubusercontent.com/8568151/48399262-2516e680-e75e-11e8-999e-bdd2144e7967.png">
]

**Comment by benknoble** [comment]
cf. #7 , #4 , #2 , ...
