### ISSUE TITLE
How to change display color of directory 

### ISSUE THREAD

**Issue by HaoyangFan** [dracula/terminal-app#9]
I like the color display setting as shown in this project's screenshot (that's also why I choose this theme)
<img width="718" alt="screen shot 2019-01-04 at 12 52 09 am" src="https://user-images.githubusercontent.com/22490077/50680083-38ef0400-0fbb-11e9-8bf9-dcb1b184769f.png">
As you can see, the color for the directory name `dracula-theme` is in `purple` while the color for git branch is `cyan`.
However, when I follow the instruction to install the theme on my terminal (I'm using Mac's own Terminal.app, zsh shell, and oh-my-zsh extension, both are the same with the terminal used in the screenshot above), I got different colors for directory name and branch name 
<img width="567" alt="screen shot 2019-01-04 at 12 59 22 am" src="https://user-images.githubusercontent.com/22490077/50680302-05f94000-0fbc-11e9-9786-dacd7ea4aa33.png">
Now the color for directory name is actually cyan while for the git branch is purple. That's not what I want. I want to change the color for directory name to be purple and git branch to be cyan, which is basically the same as project's screenshot. 

Can you provide any instruction on how to do it? Thanks

**Comment by benknoble** [comment]
Check #2 and the many issues I've marked as duplicates of it: the answer is, the screenshot on the repo was taken using a custom ZSH theme (@zenorocha can give more information).

I don't maintain any shell themes, just the terminal colorspec, which is what this repo concerns. If you want to tweak your ZSH prompt, you'll need to do so using an oh-my-zsh theme (I think), or by writing your own prompt.

You might also look into [Dracula for ZSH](https://draculatheme.com/zsh/)
